run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - godot
    - gofumpt
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  godot:
    scope: declarations
    period: true
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  gosec:
    excludes:
      - G101 # Look for hardcoded credentials
      - G204 # Audit use of command execution

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst
    - path: pkg/client/api/
      linters:
        - unused
        - goconst
        - dupl
    - linters:
        - godot
      text: "Comment should end in a period"

output:
  format: colored-line-number
  sort-results: true 