// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/AlenaMolokova/gophkeeper/pkg/client/api"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockUserServiceClientInterface is a mock of UserServiceClientInterface interface.
type MockUserServiceClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceClientInterfaceMockRecorder
	isgomock struct{}
}

// MockUserServiceClientInterfaceMockRecorder is the mock recorder for MockUserServiceClientInterface.
type MockUserServiceClientInterfaceMockRecorder struct {
	mock *MockUserServiceClientInterface
}

// NewMockUserServiceClientInterface creates a new mock instance.
func NewMockUserServiceClientInterface(ctrl *gomock.Controller) *MockUserServiceClientInterface {
	mock := &MockUserServiceClientInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceClientInterface) EXPECT() *MockUserServiceClientInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockUserServiceClientInterface) Login(ctx context.Context, req *client.LoginRequest, opts ...grpc.CallOption) (*client.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Login", varargs...)
	ret0, _ := ret[0].(*client.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceClientInterfaceMockRecorder) Login(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServiceClientInterface)(nil).Login), varargs...)
}

// Register mocks base method.
func (m *MockUserServiceClientInterface) Register(ctx context.Context, req *client.RegisterRequest, opts ...grpc.CallOption) (*client.RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Register", varargs...)
	ret0, _ := ret[0].(*client.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserServiceClientInterfaceMockRecorder) Register(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserServiceClientInterface)(nil).Register), varargs...)
}

// MockDataServiceClientInterface is a mock of DataServiceClientInterface interface.
type MockDataServiceClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDataServiceClientInterfaceMockRecorder
	isgomock struct{}
}

// MockDataServiceClientInterfaceMockRecorder is the mock recorder for MockDataServiceClientInterface.
type MockDataServiceClientInterfaceMockRecorder struct {
	mock *MockDataServiceClientInterface
}

// NewMockDataServiceClientInterface creates a new mock instance.
func NewMockDataServiceClientInterface(ctrl *gomock.Controller) *MockDataServiceClientInterface {
	mock := &MockDataServiceClientInterface{ctrl: ctrl}
	mock.recorder = &MockDataServiceClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataServiceClientInterface) EXPECT() *MockDataServiceClientInterfaceMockRecorder {
	return m.recorder
}

// AddData mocks base method.
func (m *MockDataServiceClientInterface) AddData(ctx context.Context, req *client.AddDataRequest, opts ...grpc.CallOption) (*client.AddDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddData", varargs...)
	ret0, _ := ret[0].(*client.AddDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddData indicates an expected call of AddData.
func (mr *MockDataServiceClientInterfaceMockRecorder) AddData(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddData", reflect.TypeOf((*MockDataServiceClientInterface)(nil).AddData), varargs...)
}

// DeleteData mocks base method.
func (m *MockDataServiceClientInterface) DeleteData(ctx context.Context, req *client.DeleteDataRequest, opts ...grpc.CallOption) (*client.DeleteDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteData", varargs...)
	ret0, _ := ret[0].(*client.DeleteDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataServiceClientInterfaceMockRecorder) DeleteData(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataServiceClientInterface)(nil).DeleteData), varargs...)
}

// EditData mocks base method.
func (m *MockDataServiceClientInterface) EditData(ctx context.Context, req *client.EditDataRequest, opts ...grpc.CallOption) (*client.EditDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditData", varargs...)
	ret0, _ := ret[0].(*client.EditDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditData indicates an expected call of EditData.
func (mr *MockDataServiceClientInterfaceMockRecorder) EditData(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditData", reflect.TypeOf((*MockDataServiceClientInterface)(nil).EditData), varargs...)
}

// GetData mocks base method.
func (m *MockDataServiceClientInterface) GetData(ctx context.Context, req *client.GetDataRequest, opts ...grpc.CallOption) (*client.GetDataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetData", varargs...)
	ret0, _ := ret[0].(*client.GetDataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockDataServiceClientInterfaceMockRecorder) GetData(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockDataServiceClientInterface)(nil).GetData), varargs...)
}
