// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	models "github.com/AlenaMolokova/gophkeeper/internal/shared/models"
	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockStorage) DeleteData(ctx context.Context, userID, dataID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, dataID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockStorageMockRecorder) DeleteData(ctx, userID, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockStorage)(nil).DeleteData), ctx, userID, dataID)
}

// EditData mocks base method.
func (m *MockStorage) EditData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditData indicates an expected call of EditData.
func (mr *MockStorageMockRecorder) EditData(ctx, userID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditData", reflect.TypeOf((*MockStorage)(nil).EditData), ctx, userID, data)
}

// FindDataByID mocks base method.
func (m *MockStorage) FindDataByID(ctx context.Context, userID, dataID string) (models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDataByID", ctx, userID, dataID)
	ret0, _ := ret[0].(models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDataByID indicates an expected call of FindDataByID.
func (mr *MockStorageMockRecorder) FindDataByID(ctx, userID, dataID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDataByID", reflect.TypeOf((*MockStorage)(nil).FindDataByID), ctx, userID, dataID)
}

// FindUserByEmail mocks base method.
func (m *MockStorage) FindUserByEmail(ctx context.Context, email string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockStorageMockRecorder) FindUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockStorage)(nil).FindUserByEmail), ctx, email)
}

// GetPoolStats mocks base method.
func (m *MockStorage) GetPoolStats() *PoolStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolStats")
	ret0, _ := ret[0].(*PoolStats)
	return ret0
}

// GetPoolStats indicates an expected call of GetPoolStats.
func (mr *MockStorageMockRecorder) GetPoolStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolStats", reflect.TypeOf((*MockStorage)(nil).GetPoolStats))
}

// SaveData mocks base method.
func (m *MockStorage) SaveData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveData indicates an expected call of SaveData.
func (mr *MockStorageMockRecorder) SaveData(ctx, userID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveData", reflect.TypeOf((*MockStorage)(nil).SaveData), ctx, userID, data)
}

// SaveUser mocks base method.
func (m *MockStorage) SaveUser(ctx context.Context, email, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, email, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockStorageMockRecorder) SaveUser(ctx, email, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockStorage)(nil).SaveUser), ctx, email, hash)
}
