// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/AlenaMolokova/gophkeeper/internal/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDataReader is a mock of DataReader interface.
type MockDataReader struct {
	ctrl     *gomock.Controller
	recorder *MockDataReaderMockRecorder
	isgomock struct{}
}

// MockDataReaderMockRecorder is the mock recorder for MockDataReader.
type MockDataReaderMockRecorder struct {
	mock *MockDataReader
}

// NewMockDataReader creates a new mock instance.
func NewMockDataReader(ctrl *gomock.Controller) *MockDataReader {
	mock := &MockDataReader{ctrl: ctrl}
	mock.recorder = &MockDataReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataReader) EXPECT() *MockDataReaderMockRecorder {
	return m.recorder
}

// FindDataByID mocks base method.
func (m *MockDataReader) FindDataByID(ctx context.Context, userID, dataID string) (models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDataByID", ctx, userID, dataID)
	ret0, _ := ret[0].(models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDataByID indicates an expected call of FindDataByID.
func (mr *MockDataReaderMockRecorder) FindDataByID(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDataByID", reflect.TypeOf((*MockDataReader)(nil).FindDataByID), ctx, userID, dataID)
}

// MockDataWriter is a mock of DataWriter interface.
type MockDataWriter struct {
	ctrl     *gomock.Controller
	recorder *MockDataWriterMockRecorder
	isgomock struct{}
}

// MockDataWriterMockRecorder is the mock recorder for MockDataWriter.
type MockDataWriterMockRecorder struct {
	mock *MockDataWriter
}

// NewMockDataWriter creates a new mock instance.
func NewMockDataWriter(ctrl *gomock.Controller) *MockDataWriter {
	mock := &MockDataWriter{ctrl: ctrl}
	mock.recorder = &MockDataWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataWriter) EXPECT() *MockDataWriterMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockDataWriter) DeleteData(ctx context.Context, userID, dataID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, dataID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataWriterMockRecorder) DeleteData(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataWriter)(nil).DeleteData), ctx, userID, dataID)
}

// EditData mocks base method.
func (m *MockDataWriter) EditData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditData indicates an expected call of EditData.
func (mr *MockDataWriterMockRecorder) EditData(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditData", reflect.TypeOf((*MockDataWriter)(nil).EditData), ctx, userID, data)
}

// SaveData mocks base method.
func (m *MockDataWriter) SaveData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveData indicates an expected call of SaveData.
func (mr *MockDataWriterMockRecorder) SaveData(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveData", reflect.TypeOf((*MockDataWriter)(nil).SaveData), ctx, userID, data)
}

// MockDataStorage is a mock of DataStorage interface.
type MockDataStorage struct {
	ctrl     *gomock.Controller
	recorder *MockDataStorageMockRecorder
	isgomock struct{}
}

// MockDataStorageMockRecorder is the mock recorder for MockDataStorage.
type MockDataStorageMockRecorder struct {
	mock *MockDataStorage
}

// NewMockDataStorage creates a new mock instance.
func NewMockDataStorage(ctrl *gomock.Controller) *MockDataStorage {
	mock := &MockDataStorage{ctrl: ctrl}
	mock.recorder = &MockDataStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStorage) EXPECT() *MockDataStorageMockRecorder {
	return m.recorder
}

// DeleteData mocks base method.
func (m *MockDataStorage) DeleteData(ctx context.Context, userID, dataID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, dataID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockDataStorageMockRecorder) DeleteData(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockDataStorage)(nil).DeleteData), ctx, userID, dataID)
}

// EditData mocks base method.
func (m *MockDataStorage) EditData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditData indicates an expected call of EditData.
func (mr *MockDataStorageMockRecorder) EditData(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditData", reflect.TypeOf((*MockDataStorage)(nil).EditData), ctx, userID, data)
}

// FindDataByID mocks base method.
func (m *MockDataStorage) FindDataByID(ctx context.Context, userID, dataID string) (models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDataByID", ctx, userID, dataID)
	ret0, _ := ret[0].(models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDataByID indicates an expected call of FindDataByID.
func (mr *MockDataStorageMockRecorder) FindDataByID(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDataByID", reflect.TypeOf((*MockDataStorage)(nil).FindDataByID), ctx, userID, dataID)
}

// SaveData mocks base method.
func (m *MockDataStorage) SaveData(ctx context.Context, userID string, data models.Data) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveData", ctx, userID, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveData indicates an expected call of SaveData.
func (mr *MockDataStorageMockRecorder) SaveData(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveData", reflect.TypeOf((*MockDataStorage)(nil).SaveData), ctx, userID, data)
}
