syntax = "proto3";

option go_package = "github.com/AlenaMolokova/gophkeeper/pkg/client/api";

package gophkeeper;

service GophKeeper {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc AddData(AddDataRequest) returns (AddDataResponse);
    rpc GetData(GetDataRequest) returns (GetDataResponse);
    rpc EditData(EditDataRequest) returns (EditDataResponse);
    rpc DeleteData(DeleteDataRequest) returns (DeleteDataResponse);
}

message RegisterRequest {
    string email = 1;
    string password = 2;
}

message RegisterResponse {
    string token = 1;
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
}

message AddDataRequest {
    string token = 1;
    Data data = 2;
}

message AddDataResponse {
    string id = 1;
}

message GetDataRequest {
    string token = 1;
    string id = 2;
}

message GetDataResponse {
    Data data = 1;
}

message EditDataRequest {
    string token = 1;
    Data data = 2;
}

message EditDataResponse {
    string id = 1;
}

message DeleteDataRequest {
    string token = 1;
    string id = 2;
}

message DeleteDataResponse {}

message Data {
    string id = 1;
    string type = 2; // "login", "text", "binary", "card", "otp"
    bytes payload = 3; // Encrypted data
    map<string, string> metadata = 4; // Additional metadata
    int64 timestamp = 5; // For synchronization
}